# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Integração contínua com Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Ambiente de desenvolvimento
  build-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:

      # Instala Xvfb
      - name: Instala Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      # Inicia Xvfb
      - name: Inicia Xvfb
        run: |
          Xvfb :1 -screen 0 1600x1200x24 &
          echo "DISPLAY=:1" >> $GITHUB_ENV
          echo "_JAVA_OPTIONS=-Djava.awt.headless=false" >> $GITHUB_ENV

      # Checkout
      - name: Realiza o checkout do repositório
        uses: actions/checkout@v4
      
      # JDK 17
      - name: Configura o JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Maven test
      - name: Compila o projeto com Maven
        env:
          DISPLAY: :1
          _JAVA_OPTIONS: "-Djava.awt.headless=false"
        run: mvn -B test --file pom.xml

      # Desliga Xvfb
      - name: Desliga Xvfb
        run: killall Xvfb

  # Ambiente de homologação
  build-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
    needs: build-dev
    steps:

      - name: Realiza o checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Instala Xvfb
      - name: Instala Xvfb
        run: sudo apt-get update && sudo apt-get install -y xvfb

      # Inicia Xvfb e define ambiente gráfico
      - name: Inicia Xvfb
        run: |
          Xvfb :1 -screen 0 1600x1200x24 &
          echo "DISPLAY=:1" >> $GITHUB_ENV
          echo "_JAVA_OPTIONS=-Djava.awt.headless=false" >> $GITHUB_ENV

      # JDK 17
      - name: Configura o JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Maven test
      - name: Testa o projeto com Maven
        env:
          DISPLAY: :1
          _JAVA_OPTIONS: "-Djava.awt.headless=false"
        run: mvn -B test --file pom.xml

      # Cache SonarCloud
      - name: Cache dos pacotes do SonarCloud
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      # Cache Maven
      - name: Cache dos pacotes do Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # Maven + Jacoco + Sonar
      - name: Verifica o projeto com Maven e Jacoco
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          DISPLAY: :1
          _JAVA_OPTIONS: "-Djava.awt.headless=false"
        run: |
          mvn -B verify \
            org.jacoco:jacoco-maven-plugin:prepare-agent \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=amandaespindola_A3-Unisul-Gestao-de-Qualidade \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  # Ambiente de produção
  build-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: build-hmg
    steps:

      - name: Realiza o checkout do repositório
        uses: actions/checkout@v3

      - name: Configura o JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Maven package (testes já rodaram)
      - name: Empacota o projeto com Maven
        run: mvn -B package --file pom.xml -DskipTests

      - name: Crie uma pasta temporária de downloads de artefatos
        run: mkdir staging

      - name: Copia os artefatos a serem publicados na pasta temporária
        run: cp target/*jar-with-dependencies.jar staging

      - name: Usa Upload Artifact do GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
