# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Integração contínua com Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # Jobs do ambiente de desenvolvimento
  build-dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    steps:
      # Terminal virtual 1 para a tela 0 com as dimensões especificadas
      - name: Configura xvfb para tela 0
        run: Xvfb :1 -screen 0 1600x1200x24 &
      
      # Utiliza a action checkout para fazer o git clone no runner
      - name: Realiza o checkout do repositório
        uses: actions/checkout@v4
      
      # Utiliza a action setup-java para configurar a versão necessária do JDK
      - name: Configura o JDK 18
        uses: actions/setup-java@v4
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: maven
      
      # Executa a compilação e testes do projeto com o Maven no runner
      - name: Compila o projeto com Maven
        env:
          # Roda a aplicação no terminal virtual 1 do Xvfb
          DISPLAY: :1
        run: mvn -B test --file pom.xml
      
      # Desliga o Xvfb
      - name: Desliga Xvfb
        run: killall Xvfb

  # Jobs do ambiente de homologação
  build-hmg:
    runs-on: ubuntu-latest
    environment:
      name: hmg
    needs: build-dev
    steps:
      - name: Realiza o checkout do repositório
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Configura o JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Testa o projeto com Maven
        run: mvn -B test --file pom.xml   

        # Executa os passos da análise do código com o sonarcube
      - name: Cache dos pacotes do SonarCloud
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar
      
      - name: Cache dos pacotes do Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2
      
      - name: Verifica o projeto com Maven e Jacoco
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar -Dsonar.projectKey=amandaespindola_A3-Unisul-Gestao-de-Qualidade org.jacoco:jacoco-maven-plugin:prepare-agent -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml

  # Jobs do ambiente de produção
  build-prd:
    runs-on: ubuntu-latest
    environment:
      name: prd
    needs: build-hmg
    steps:
      - name: Realiza o checkout do repositório
        uses: actions/checkout@v3
      - name: Configura o JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      # Executa o empacotamento do projeto com o Maven.
      # O parâmetro -DskipTests pula os testes pois já foram executados no ambiente anterior.
      - name: Empacota o projeto com Maven
        run: mvn -B package --file pom.xml -DskipTests
      # Cria o artefato de download
      - name: Crie uma pasta temporária de downloads de artefatos
        run: mkdir staging
      - name: Copia os artefatos a serem publicados na pasta temporária
        run: cp target/*jar-with-dependencies.jar staging
      - name: Usa Upload Artifact do GitHub Action
        uses: actions/upload-artifact@v4
        with:
          name: Package
          path: staging
